import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.JOptionPane;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Members.java
 *
 * Created on May 30, 2019, 3:03:28 PM
 */

/**
 *
 * @author vaio
 */
public class Members extends javax.swing.JFrame {
    private String member_no;

    /** Creates new form Members */
    public Members() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        butcategory = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        txtmem = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        rbstutdent = new javax.swing.JRadioButton();
        rbfaculty = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        txtdate = new javax.swing.JTextField();
        butaddmem = new javax.swing.JButton();
        butclear = new javax.swing.JButton();
        buthome = new javax.swing.JButton();
        butexit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("  Name ");

        jLabel2.setText("  Membership No.");

        jLabel3.setText(" Category");

        butcategory.add(rbstutdent);
        rbstutdent.setText("Student");

        butcategory.add(rbfaculty);
        rbfaculty.setText("Faculty");
        rbfaculty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbfacultyActionPerformed(evt);
            }
        });

        jLabel4.setText("Date of joining");

        butaddmem.setText("Add Member");
        butaddmem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butaddmemActionPerformed(evt);
            }
        });

        butclear.setText("Clear");
        butclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butclearActionPerformed(evt);
            }
        });

        buthome.setText("Home page");
        buthome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buthomeActionPerformed(evt);
            }
        });

        butexit.setText("Exit");
        butexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butexitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(140, 140, 140)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtmem)
                            .addComponent(txtname, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE))
                        .addContainerGap(567, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(152, 152, 152)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbstutdent)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 188, Short.MAX_VALUE)
                                .addComponent(rbfaculty)
                                .addGap(324, 324, 324))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtdate, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(butclear)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 148, Short.MAX_VALUE)
                .addComponent(buthome)
                .addGap(99, 99, 99)
                .addComponent(butexit)
                .addGap(353, 353, 353))
            .addGroup(layout.createSequentialGroup()
                .addGap(237, 237, 237)
                .addComponent(butaddmem, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(600, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtmem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(rbstutdent)
                    .addComponent(rbfaculty))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(butaddmem)
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butclear)
                    .addComponent(butexit)
                    .addComponent(buthome))
                .addContainerGap(101, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbfacultyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbfacultyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbfacultyActionPerformed

    private void butaddmemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butaddmemActionPerformed
int mem = Integer.parseInt(txtmem.getText());
String name = txtname.getText();
String date_join = txtdate.getText();
if (date_join.isEmpty())
  {
JOptionPane.showMessageDialog(this,"Please enter date");
  }
else
  {
if (date_join.contains("__/__/____"))
       {
JOptionPane.showMessageDialog(this,"Enter date in required format YYYY/MM/DD");
       }
  }

String category = null;
if(rbstutdent.isSelected())
{
category = "Student";
}
else if(rbfaculty.isSelected())
{
category = "Faculty";
}
try
{
Class.forName("java.sql.DriverManager");
    Connection con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/Library_mang","root","admin");
    Statement stmt = (Statement)con.createStatement();
    String add= "Insert into members values('"+mem+"','"+name+"','"+category+"','"+date_join+"');";
     stmt.execute(add);
    JOptionPane.showMessageDialog(this,"Welcome to the Library.\n Member added successfuly.");
    
 }
catch(Exception e)
{
JOptionPane.showMessageDialog(this,e.getMessage());
}



        // TODO add your handling code here:
    }//GEN-LAST:event_butaddmemActionPerformed

    private void butexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butexitActionPerformed
System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_butexitActionPerformed

    private void buthomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buthomeActionPerformed
home_page Members =  new home_page();
Members.setVisible(true);
this.setVisible(false);

        // TODO add your handling code here:
    }//GEN-LAST:event_buthomeActionPerformed

    private void butclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butclearActionPerformed
txtname.setText("");
txtmem.setText("");
txtdate.setText("");
butcategory.clearSelection();

        // TODO add your handling code here:
    }//GEN-LAST:event_butclearActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Members().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butaddmem;
    private javax.swing.ButtonGroup butcategory;
    private javax.swing.JButton butclear;
    private javax.swing.JButton butexit;
    private javax.swing.JButton buthome;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton rbfaculty;
    private javax.swing.JRadioButton rbstutdent;
    private javax.swing.JTextField txtdate;
    private javax.swing.JTextField txtmem;
    private javax.swing.JTextField txtname;
    // End of variables declaration//GEN-END:variables

}
