import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Return_details.java
 *
 * Created on May 30, 2019, 3:22:26 PM
 */

/**
 *
 * @author vaio
 */
public class Return_details extends javax.swing.JFrame {

    /** Creates new form Return_details */
    public Return_details() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        txtdate = new javax.swing.JTextField();
        butreturn = new javax.swing.JButton();
        butsub = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Book id ");

        jLabel2.setText("  Current date ");

        butreturn.setText("Check The Return date");
        butreturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butreturnActionPerformed(evt);
            }
        });

        butsub.setText("Submit Book");
        butsub.setEnabled(false);
        butsub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butsubActionPerformed(evt);
            }
        });

        jButton3.setText("Clear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Home page");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Exit");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 143, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(122, 122, 122)
                .addComponent(jButton5)
                .addGap(172, 172, 172))
            .addGroup(layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(butreturn, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(butsub))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtid, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtdate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE))))
                .addContainerGap(178, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(105, 105, 105)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butsub)
                    .addComponent(butreturn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton5)
                    .addComponent(jButton4))
                .addGap(85, 85, 85))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butreturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butreturnActionPerformed

String date = txtdate.getText();
if (date.isEmpty())
  {
     JOptionPane.showMessageDialog(this,"Please enter date");
  }
else
  {
     if (date.contains("__/__/____"))
       {
           JOptionPane.showMessageDialog(this,"Enter date in required format YYYY/MM/DD");
       }
     if (date.contains("__/__/__"))
       {
           JOptionPane.showMessageDialog(this,"Enter date in required format YYYY/MM/DD");
       }
String return_date = "NULL",book_id;
book_id = txtid.getText();
try
{
    Class.forName("java.sql.DriverManager");
    Connection con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/Library_mang","root","admin");
    Statement stmt = (Statement)con.createStatement();
    String query = "Select return_date from return_details where book_id = '"+book_id+"';";
   ResultSet rs = stmt.executeQuery(query);
   if(rs.next())
   {
       return_date = rs.getString("return_date");
   }
   if(Integer.parseInt(date) <= Integer.parseInt(return_date))
 {
    butsub.setEnabled(true);
    JOptionPane.showMessageDialog(this,"Book successfully returned.");
 }
   else
    JOptionPane.showMessageDialog(this,"You are late to submit book. Kindly pay the late fee.");
}
catch(Exception e)
{
    JOptionPane.showMessageDialog(this,e.getMessage());
}
    }
  // TODO add your handling code here:
    }//GEN-LAST:event_butreturnActionPerformed

private void butsubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butsubActionPerformed
String book_id,issue_date = "NULL",return_date = "NULL";
int member_no = 0;
book_id = txtid.getText();
try
{
    Class.forName("java.sql.DriverManager");
    Connection con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/Library_mang","root","admin");
    Statement stmt = (Statement)con.createStatement();
    String query1 = "Update book_details set quantity  =quantity+1 where book_id = '"+book_id+"';";
    stmt.executeUpdate(query1);
    String query = "Select * from issue_details where book_id = '"+book_id+"';";
   ResultSet rs = stmt.executeQuery(query);
   if(rs.next())
   {
       return_date = rs.getString("return_date");
       issue_date = rs.getString("issue_date");
       member_no = rs.getInt("member_no");
   }
   String query2 = "Insert into return_details values('"+book_id+"','"+member_no+"','"+issue_date+"','"+return_date+"');";
   stmt.executeQuery(query2);
}
catch(Exception e)
{
    JOptionPane.showMessageDialog(this,e.getMessage());
}

    // TODO add your handling code here:
}//GEN-LAST:event_butsubActionPerformed

private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
System.exit(0);
    // TODO add your handling code here:
}//GEN-LAST:event_jButton5ActionPerformed

private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
           home_page Return_details =  new home_page();
           Return_details.setVisible(true);
           this.setVisible(false);

    // TODO add your handling code here:
}//GEN-LAST:event_jButton4ActionPerformed

private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
txtid.setText("");
txtdate.setText("");
butsub.setEnabled(false);

    // TODO add your handling code here:
}//GEN-LAST:event_jButton3ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Return_details().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butreturn;
    private javax.swing.JButton butsub;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtdate;
    private javax.swing.JTextField txtid;
    // End of variables declaration//GEN-END:variables

}
